# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_deep_feedback_learning', [dirname(__file__)])
        except ImportError:
            import _deep_feedback_learning
            return _deep_feedback_learning
        if fp is not None:
            try:
                _mod = imp.load_module('_deep_feedback_learning', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _deep_feedback_learning = swig_import_helper()
    del swig_import_helper
else:
    import _deep_feedback_learning
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


class DeepFeedbackLearning(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DeepFeedbackLearning, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DeepFeedbackLearning, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _deep_feedback_learning.new_DeepFeedbackLearning(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _deep_feedback_learning.delete_DeepFeedbackLearning
    __del__ = lambda self: None
    backprop = _deep_feedback_learning.DeepFeedbackLearning_backprop
    ico = _deep_feedback_learning.DeepFeedbackLearning_ico

    def doStep(self, *args) -> "void":
        return _deep_feedback_learning.DeepFeedbackLearning_doStep(self, *args)

    def getOutput(self, index: 'int') -> "double":
        return _deep_feedback_learning.DeepFeedbackLearning_getOutput(self, index)

    def setLearningRate(self, learningRate: 'double') -> "void":
        return _deep_feedback_learning.DeepFeedbackLearning_setLearningRate(self, learningRate)

    def setLearningRateDiscountFactor(self, _learningRateDiscountFactor: 'double') -> "void":
        return _deep_feedback_learning.DeepFeedbackLearning_setLearningRateDiscountFactor(self, _learningRateDiscountFactor)

    def setMomentum(self, momentum: 'double') -> "void":
        return _deep_feedback_learning.DeepFeedbackLearning_setMomentum(self, momentum)

    def setAlgorithm(self, _algorithm: 'DeepFeedbackLearning::Algorithm') -> "void":
        return _deep_feedback_learning.DeepFeedbackLearning_setAlgorithm(self, _algorithm)

    def getAlgorithm(self) -> "DeepFeedbackLearning::Algorithm":
        return _deep_feedback_learning.DeepFeedbackLearning_getAlgorithm(self)

    def initWeights(self, *args) -> "void":
        return _deep_feedback_learning.DeepFeedbackLearning_initWeights(self, *args)

    def seedRandom(self, s: 'int') -> "void":
        return _deep_feedback_learning.DeepFeedbackLearning_seedRandom(self, s)

    def setBias(self, _bias: 'double') -> "void":
        return _deep_feedback_learning.DeepFeedbackLearning_setBias(self, _bias)

    def getNumHidLayers(self) -> "int":
        return _deep_feedback_learning.DeepFeedbackLearning_getNumHidLayers(self)

    def getNumLayers(self) -> "int":
        return _deep_feedback_learning.DeepFeedbackLearning_getNumLayers(self)

    def getLayer(self, i: 'int') -> "Layer *":
        return _deep_feedback_learning.DeepFeedbackLearning_getLayer(self, i)

    def getOutputLayer(self) -> "Layer *":
        return _deep_feedback_learning.DeepFeedbackLearning_getOutputLayer(self)

    def getLayers(self) -> "Layer **":
        return _deep_feedback_learning.DeepFeedbackLearning_getLayers(self)

    def setUseDerivative(self, useIt: 'int') -> "void":
        return _deep_feedback_learning.DeepFeedbackLearning_setUseDerivative(self, useIt)

    def saveModel(self, name: 'char const *') -> "bool":
        return _deep_feedback_learning.DeepFeedbackLearning_saveModel(self, name)

    def loadModel(self, name: 'char const *') -> "bool":
        return _deep_feedback_learning.DeepFeedbackLearning_loadModel(self, name)
DeepFeedbackLearning_swigregister = _deep_feedback_learning.DeepFeedbackLearning_swigregister
DeepFeedbackLearning_swigregister(DeepFeedbackLearning)

class Layer(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Layer, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Layer, name)
    __repr__ = _swig_repr

    def __init__(self, _nNeurons: 'int', _nInputs: 'int', _nFilters: 'int'=0, _minT: 'double'=0, _maxT: 'double'=0):
        this = _deep_feedback_learning.new_Layer(_nNeurons, _nInputs, _nFilters, _minT, _maxT)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _deep_feedback_learning.delete_Layer
    __del__ = lambda self: None

    def calcOutputs(self) -> "void":
        return _deep_feedback_learning.Layer_calcOutputs(self)

    def doLearning(self) -> "void":
        return _deep_feedback_learning.Layer_doLearning(self)

    def setError(self, *args) -> "void":
        return _deep_feedback_learning.Layer_setError(self, *args)

    def setErrors(self, _errors: 'double *') -> "void":
        return _deep_feedback_learning.Layer_setErrors(self, _errors)

    def getError(self, i: 'int') -> "double":
        return _deep_feedback_learning.Layer_getError(self, i)

    def setBias(self, _bias: 'double') -> "void":
        return _deep_feedback_learning.Layer_setBias(self, _bias)

    def setUseDerivative(self, useIt: 'int') -> "void":
        return _deep_feedback_learning.Layer_setUseDerivative(self, useIt)

    def setInput(self, inputIndex: 'int', input: 'double') -> "void":
        return _deep_feedback_learning.Layer_setInput(self, inputIndex, input)

    def setInputs(self, _inputs: 'double *') -> "void":
        return _deep_feedback_learning.Layer_setInputs(self, _inputs)

    def setLearningRate(self, _learningRate: 'double') -> "void":
        return _deep_feedback_learning.Layer_setLearningRate(self, _learningRate)

    def setActivationFunction(self, _activationFunction: 'Neuron::ActivationFunction') -> "void":
        return _deep_feedback_learning.Layer_setActivationFunction(self, _activationFunction)

    def setMomentum(self, _momentum: 'double') -> "void":
        return _deep_feedback_learning.Layer_setMomentum(self, _momentum)

    def initWeights(self, *args) -> "void":
        return _deep_feedback_learning.Layer_initWeights(self, *args)

    def getOutput(self, index: 'int') -> "double":
        return _deep_feedback_learning.Layer_getOutput(self, index)

    def getNeuron(self, index: 'int') -> "Neuron *":
        return _deep_feedback_learning.Layer_getNeuron(self, index)

    def getNneurons(self) -> "int":
        return _deep_feedback_learning.Layer_getNneurons(self)

    def getNinputs(self) -> "int":
        return _deep_feedback_learning.Layer_getNinputs(self)

    def setConvolution(self, width: 'int', height: 'int') -> "void":
        return _deep_feedback_learning.Layer_setConvolution(self, width, height)

    def setMaxDetLayer(self, _m: 'int') -> "void":
        return _deep_feedback_learning.Layer_setMaxDetLayer(self, _m)

    def setNormaliseWeights(self, _normaliseWeights: 'int') -> "void":
        return _deep_feedback_learning.Layer_setNormaliseWeights(self, _normaliseWeights)

    def setDebugInfo(self, layerIndex: 'int') -> "void":
        return _deep_feedback_learning.Layer_setDebugInfo(self, layerIndex)

    def setStep(self, step: 'long') -> "void":
        return _deep_feedback_learning.Layer_setStep(self, step)

    def getWeightDistanceFromInitialWeights(self) -> "double":
        return _deep_feedback_learning.Layer_getWeightDistanceFromInitialWeights(self)
Layer_swigregister = _deep_feedback_learning.Layer_swigregister
Layer_swigregister(Layer)

class Neuron(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Neuron, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Neuron, name)
    __repr__ = _swig_repr

    def __init__(self, _nInputs: 'int', _nFilters: 'int'=0, _minT: 'double'=0, _maxT: 'double'=0):
        this = _deep_feedback_learning.new_Neuron(_nInputs, _nFilters, _minT, _maxT)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _deep_feedback_learning.delete_Neuron
    __del__ = lambda self: None

    def calcOutput(self) -> "void":
        return _deep_feedback_learning.Neuron_calcOutput(self)
    __swig_getmethods__["calcOutputThread"] = lambda x: _deep_feedback_learning.Neuron_calcOutputThread
    if _newclass:
        calcOutputThread = staticmethod(_deep_feedback_learning.Neuron_calcOutputThread)

    def doLearning(self) -> "void":
        return _deep_feedback_learning.Neuron_doLearning(self)
    __swig_getmethods__["doLearningThread"] = lambda x: _deep_feedback_learning.Neuron_doLearningThread
    if _newclass:
        doLearningThread = staticmethod(_deep_feedback_learning.Neuron_doLearningThread)

    def doMaxDet(self) -> "void":
        return _deep_feedback_learning.Neuron_doMaxDet(self)
    __swig_getmethods__["doMaxDetThread"] = lambda x: _deep_feedback_learning.Neuron_doMaxDetThread
    if _newclass:
        doMaxDetThread = staticmethod(_deep_feedback_learning.Neuron_doMaxDetThread)
    MAX_OUTPUT_RANDOM = _deep_feedback_learning.Neuron_MAX_OUTPUT_RANDOM
    MAX_WEIGHT_RANDOM = _deep_feedback_learning.Neuron_MAX_WEIGHT_RANDOM
    MAX_OUTPUT_CONST = _deep_feedback_learning.Neuron_MAX_OUTPUT_CONST
    CONST_WEIGHTS = _deep_feedback_learning.Neuron_CONST_WEIGHTS

    def initWeights(self, *args) -> "void":
        return _deep_feedback_learning.Neuron_initWeights(self, *args)
    LINEAR = _deep_feedback_learning.Neuron_LINEAR
    TANH = _deep_feedback_learning.Neuron_TANH
    RELU = _deep_feedback_learning.Neuron_RELU
    REMAXLU = _deep_feedback_learning.Neuron_REMAXLU

    def setActivationFunction(self, _activationFunction: 'Neuron::ActivationFunction') -> "void":
        return _deep_feedback_learning.Neuron_setActivationFunction(self, _activationFunction)

    def dActivation(self) -> "double":
        return _deep_feedback_learning.Neuron_dActivation(self)

    def getMinWeightValue(self) -> "double":
        return _deep_feedback_learning.Neuron_getMinWeightValue(self)

    def getMaxWeightValue(self) -> "double":
        return _deep_feedback_learning.Neuron_getMaxWeightValue(self)

    def getWeightDistanceFromInitialWeights(self) -> "double":
        return _deep_feedback_learning.Neuron_getWeightDistanceFromInitialWeights(self)

    def getOutput(self) -> "double":
        return _deep_feedback_learning.Neuron_getOutput(self)

    def getSum(self) -> "double":
        return _deep_feedback_learning.Neuron_getSum(self)

    def getWeight(self, _index: 'int', _filter: 'int') -> "double":
        return _deep_feedback_learning.Neuron_getWeight(self, _index, _filter)

    def setWeight(self, _index: 'int', _weight: 'double', _filter: 'int') -> "void":
        return _deep_feedback_learning.Neuron_setWeight(self, _index, _weight, _filter)

    def setError(self, _error: 'double') -> "void":
        return _deep_feedback_learning.Neuron_setError(self, _error)

    def getError(self) -> "double":
        return _deep_feedback_learning.Neuron_getError(self)

    def setInput(self, _index: 'int', _value: 'double') -> "void":
        return _deep_feedback_learning.Neuron_setInput(self, _index, _value)

    def getInput(self, _index: 'int') -> "double":
        return _deep_feedback_learning.Neuron_getInput(self, _index)

    def getBiasWeight(self) -> "double":
        return _deep_feedback_learning.Neuron_getBiasWeight(self)

    def setBiasWeight(self, _biasweight: 'double') -> "void":
        return _deep_feedback_learning.Neuron_setBiasWeight(self, _biasweight)

    def setBias(self, _bias: 'double') -> "void":
        return _deep_feedback_learning.Neuron_setBias(self, _bias)

    def setLearningRate(self, _learningrate: 'double') -> "void":
        return _deep_feedback_learning.Neuron_setLearningRate(self, _learningrate)

    def setMomentum(self, _momentum: 'double') -> "void":
        return _deep_feedback_learning.Neuron_setMomentum(self, _momentum)

    def setUseDerivative(self, _useDerivative: 'int') -> "void":
        return _deep_feedback_learning.Neuron_setUseDerivative(self, _useDerivative)

    def getNinputs(self) -> "int":
        return _deep_feedback_learning.Neuron_getNinputs(self)

    def getNfilters(self) -> "int":
        return _deep_feedback_learning.Neuron_getNfilters(self)

    def getAvgWeight(self, _input: 'int') -> "double":
        return _deep_feedback_learning.Neuron_getAvgWeight(self, _input)

    def getAvgWeightChange(self, *args) -> "double":
        return _deep_feedback_learning.Neuron_getAvgWeightChange(self, *args)

    def setGeometry(self, _width: 'int', _height: 'int') -> "void":
        return _deep_feedback_learning.Neuron_setGeometry(self, _width, _height)

    def setMask(self, *args) -> "void":
        return _deep_feedback_learning.Neuron_setMask(self, *args)

    def getMask(self, *args) -> "unsigned char":
        return _deep_feedback_learning.Neuron_getMask(self, *args)

    def getEuclideanNormOfWeightVector(self) -> "double":
        return _deep_feedback_learning.Neuron_getEuclideanNormOfWeightVector(self)

    def getManhattanNormOfWeightVector(self) -> "double":
        return _deep_feedback_learning.Neuron_getManhattanNormOfWeightVector(self)

    def getAverageOfWeightVector(self) -> "double":
        return _deep_feedback_learning.Neuron_getAverageOfWeightVector(self)

    def normaliseWeights(self) -> "void":
        return _deep_feedback_learning.Neuron_normaliseWeights(self)

    def saveInitialWeights(self) -> "void":
        return _deep_feedback_learning.Neuron_saveInitialWeights(self)

    def setDebugInfo(self, _layerIndex: 'int', _neuronIndex: 'int') -> "void":
        return _deep_feedback_learning.Neuron_setDebugInfo(self, _layerIndex, _neuronIndex)

    def setStep(self, _step: 'long') -> "void":
        return _deep_feedback_learning.Neuron_setStep(self, _step)
Neuron_swigregister = _deep_feedback_learning.Neuron_swigregister
Neuron_swigregister(Neuron)

def Neuron_calcOutputThread(object: 'void *') -> "void *":
    return _deep_feedback_learning.Neuron_calcOutputThread(object)
Neuron_calcOutputThread = _deep_feedback_learning.Neuron_calcOutputThread

def Neuron_doLearningThread(object: 'void *') -> "void *":
    return _deep_feedback_learning.Neuron_doLearningThread(object)
Neuron_doLearningThread = _deep_feedback_learning.Neuron_doLearningThread

def Neuron_doMaxDetThread(object: 'void *') -> "void *":
    return _deep_feedback_learning.Neuron_doMaxDetThread(object)
Neuron_doMaxDetThread = _deep_feedback_learning.Neuron_doMaxDetThread

# This file is compatible with both classic and new-style classes.


